name = "feelify"
main = "worker.js"
compatibility_date = "2025-04-08"

[ai]
entrypoint = "worker.js"

[vars]
OPENROUTER_API_KEY = "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" # Add your API key here
